2022新歓の追加/2021新歓の削除
HUITGroup/huitgroup.github.io pull request #19
Opened 2022-03-11 12:14 UTC by negitorogithub

2021 新歓の削除と2022新歓情報(日時だけ)の追加
小見出しの追加

2022-03-11 15:08 UTC, karintou8710 commented on index.md
> +Twitter: [@huitgroup](https://twitter.com/huitgroup)
細かいですが、Twitterの見出しは新規入会の下にするのはどうですか？
Twitterはリンク的な感じなので下でいいと思いました。

2022-03-15 07:19 UTC, karintou8710 approved these changes

2022-03-15 10:50 UTC, Al-Mikan requested changes

2022-03-15 10:50 UTC, Al-Mikan commented on index.md
> +時間は 19:00 ~ 21:00 を予定しています。内容は追って更新されます。
「更新します」の方がいいかも！

2022-03-20 08:49 UTC, Al-Mikan approved these changes

2022-03-20 08:49 UTC, merged

2022-03-22 11:00 UTC, negitorogithub commented
@Al-Mikan 
すいません、リクエストの反映忘れてました...
新しい方で反映しておきます!