Add ISUCON-BOOK dedication post
HUITGroup/huitgroup.github.io pull request #30
Opened 2022-05-31 11:50 UTC by karintou8710

ISUCON本が届いたので記事を書きました。

2022-05-31 12:16 UTC, Al-Mikan approved these changes
頑張って１！

2022-05-31 12:16 UTC, USK314 requested changes
2点よろしくお願いします！

2022-05-31 12:16 UTC, USK314 commented on _posts/2022/2022-05-31-isuconbook_thank.md
> +ご恵贈いただきありがとうございます！
これどなたから献本していただいたかもあった方が良くないですかね

2022-05-31 12:16 UTC, USK314 commented on _posts/2022/2022-05-31-isuconbook_thank.md
> +ご恵贈いただきありがとうございます！
traPのtemmaさんから～ということで良い気がしますが「技術評論社様から～」の方が良い可能性もありますね。必要そうであれば確認します。

2022-05-31 12:16 UTC, USK314 commented on _posts/2022/2022-05-31-isuconbook_thank.md
> +「達人が教える Web パフォーマンスチューニング　〜ISUCON から学ぶ高速化の実践」が届きました！
https://www.amazon.co.jp/dp/4297128462

こちらのリンクも載せておくと良いと思います！

2022-05-31 12:20 UTC, karintou8710 commented on _posts/2022/2022-05-31-isuconbook_thank.md
> +ご恵贈いただきありがとうございます！
そうですね！
届いたときのご依頼主が技術評論社様でしたので、そちらに書き換えます。

2022-06-01 12:13 UTC, USK314 approved these changes

2022-06-02 01:32 UTC, merged