indexを最新の内容に更新
HUITGroup/huitgroup.github.io pull request #43
Opened 2023-10-17 08:36 UTC by sugarasot

「これまでの活動」を2023年にこれまで行ってきた内容で置き換えました
その他修正＆追記

2023-10-17 12:37 UTC, noriHanda requested changes
ないすう！

2023-10-17 12:37 UTC, noriHanda commented on _pages/index.md
> +- 10 月 Progate Path ハンズオン
次行ではILさんとのコラボと明記しているのでこちらもProgateさんとのコラボと明記すると良さそうです

2023-10-17 12:49 UTC, sugarasot commented on _pages/index.md
> +- 10 月 Progate Path ハンズオン
修正しました

2023-11-10 20:14 UTC, sugarasot commented on _pages/index.md
> +- 10 月 Progate Path ハンズオン
また修正しました

2023-11-14 10:22 UTC, noriHanda commented on _pages/index.md
> +- 10 月 Progate Path ハンズオン
最高！

2023-11-14 10:23 UTC, noriHanda approved these changes
LGTM!!!!

2023-11-14 10:24 UTC, merged